# Azure CI/CD pipeline config file
# https://aka.ms/yaml

# Trigger builds on master branch
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

trigger:
- master

# We can run multiple jobs in parallel.
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Provide a name for the job
- job: Linux
  # The VM image to use for the hosted agent. For a list of possible agents
  # see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
  # You can see the software installed on each agent at the same link.
  pool:
    vmImage: 'ubuntu-latest'
  # The steps to run to execute the build.
  steps:
  - script: echo $VCPKG_INSTALLATION_ROOT
  #- script: vcpkg install opencv[ffmpeg]:x64-linux nlopt:x64-linux
  #  displayName: vcpkg install dependencies
  - task: CMake@1
    inputs:
      workingDirectory: build
      cmakeArgs: ..

# Provide a name for the job
- job: Windows
  # The VM image to use for the hosted agent. For a list of possible agents
  # see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
  # You can see the software installed on each agent at the same link.
  pool:
    vmImage: 'vs2017-win2016'
  # The steps to run to execute the build.
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '-G "Visual Studio 15 2017 Win64"'
